### ISSUE TITLE
How to change Icons

### ISSUE THREAD

**Issue by philipp-kremer** [p0fi/gitlab-stats-for-scribtable#4]
Hello @p0fi,

i just checked your code because i want to build something similar for GitHub.

My Question is how did you insert the Images Properly?

I didn't find any good documentation for that. Did you just encode the url to the Icons? I tried do decode these Base64 String and thougt maybe you store the pictures anywhere and get back to them.

Appreciate your Help asap. 👍🏼

**Comment by p0fi** [comment]
Hey 👋 

That's pretty simple actually. I used an online base64 encoder like https://www.base64-image.de

Just drop your image in there and press <kbd>show code</kbd>. You will see some output like this:

```
data:image/png;base64,iVBORw0KGgoAFnwBnoBQP/AhtWKNy.......
```

Just copy everything after the comma and you are good to go 🙂

**Comment by philipp-kremer** [comment]
Thanks for your Help!

But one Last Question, did you use svg or png/jpeg? If i would use the github logo as svg the base64 String is way to long for user who wants to copy that in scriptable.

**Comment by p0fi** [comment]
I used `.png`. And yes the strings are enormous. 

Today I usually don't do that anymore. I better use online images, download and cache them to local disc.

**Comment by philipp-kremer** [comment]
Thank you very much. That helped alot
